<template>
<div class="relative-wrap" >
<div class="relative" style="background-color:#20A0FF">
<h2 >部门首页</h2>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Deleniti natus officia ab debitis laudantium eveniet laboriosam molestias maiores officiis autem suscipit totam, architecto, quisquam consequuntur, dolore. Iure doloribus, accusantium cum?</p>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. In veritatis id eveniet harum odit ad non fuga quibusdam dolorem soluta distinctio optio mollitia veniam quo, quas, ullam temporibus labore. Corporis!</p>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus repellat aperiam quia eligendi! Aliquid eos quod dolorum veniam aut officia vitae ea atque fugiat illum iusto sit iste architecto sed perferendis delectus facere eius hic, culpa libero tempora eligendi, corporis optio? Officiis vero voluptatem deserunt, dolore consectetur libero repellat veritatis dolorem nisi obcaecati laudantium repudiandae perspiciatis nemo commodi eaque odio, ea perferendis! Animi sunt labore tempora asperiores reiciendis odit tenetur, et autem quod magni, at cupiditate quo distinctio. Expedita consequatur distinctio facilis facere adipisci dolorum quod ut eligendi maxime culpa, placeat natus animi sed, illo eos, maiores vero cumque ab.</p>
<p>Eum assumenda, minima qui voluptas debitis, nostrum saepe atque ad accusantium consequuntur cumque harum unde sint, eligendi tempora necessitatibus vitae dicta! Architecto reiciendis debitis eaque mollitia tenetur quaerat natus, sint labore quia porro dolorem deserunt, aut eius quisquam nobis minima iste ab optio inventore non molestias nesciunt accusantium. Mollitia at, eaque omnis natus impedit recusandae fugit veritatis? In saepe dolore rerum voluptate nihil at animi quisquam ea eligendi modi perferendis dicta dolor, nobis, sunt nostrum excepturi sint architecto laudantium est ab iste molestias laboriosam facilis! Odit nihil debitis possimus dolores ex, labore, libero cupiditate rerum provident expedita cum totam dicta!</p>
<p>Nesciunt libero, quam, suscipit debitis eius, sequi repellendus recusandae ipsa porro eveniet quaerat minus blanditiis aliquam perspiciatis cum enim nemo harum. Nesciunt in corporis beatae quos nam, adipisci non praesentium fugiat nostrum tempore, soluta autem nisi omnis exercitationem, possimus mollitia laudantium nemo suscipit ut amet, neque voluptatum saepe! Dignissimos adipisci magni recusandae eligendi soluta, beatae, mollitia quidem commodi! Dolor quo, ea laboriosam cum dolore beatae, facilis quas. Aut reiciendis harum pariatur reprehenderit, ea, doloribus quae, aspernatur porro eligendi quam, asperiores quisquam iusto veniam suscipit esse modi assumenda inventore adipisci officiis alias cum et cumque eveniet! Quasi ipsa velit laborum, asperiores!</p>
<p>Doloremque officia hic iusto aliquid blanditiis nemo nostrum vitae, quasi aspernatur incidunt repellendus quisquam cum, illo? Dicta corrupti quam, repudiandae facilis provident fugit quo eum placeat animi, culpa enim natus nobis assumenda, fugiat! Ad quas aperiam nam dignissimos beatae, distinctio, nesciunt iure odit quae blanditiis iusto similique. Reprehenderit ab nam, nemo aliquid error veniam, porro atque vel distinctio repudiandae dolores quaerat, quae suscipit, quam! Praesentium sit cum, eum molestias numquam illum. Itaque amet laudantium blanditiis nulla nesciunt architecto provident, reiciendis dignissimos, rerum cumque, expedita voluptatum ipsum? Explicabo asperiores, porro neque accusamus modi voluptatem eaque vitae. Eum similique omnis unde, sed.</p>
<p>Adipisci quidem molestias quasi atque distinctio inventore aspernatur laborum voluptates aliquam dolorem quam aperiam minima eos eius officia impedit sequi, voluptatem, eveniet est molestiae ratione fugiat quis. Unde, totam porro fuga, doloribus incidunt provident temporibus qui obcaecati labore, tempora optio ullam ipsa minima earum sit nulla quidem hic vero! Rerum minus magni, porro cupiditate itaque incidunt fugiat accusamus a deleniti quasi perferendis provident illo vero odio, voluptatibus debitis facere fugit dolorum, numquam nostrum quod placeat. Quibusdam inventore asperiores, commodi esse tempore voluptates, dolores unde cupiditate doloremque nihil? Reprehenderit dolorum incidunt neque eveniet error. Nobis facere velit beatae esse harum, perspiciatis!</p>
<p>Soluta, vel fugiat ducimus voluptate fugit facilis sequi quos cupiditate natus sunt, tempore dolorum quasi modi magnam? Nostrum maxime a reiciendis rerum natus. Laboriosam vitae architecto molestias porro debitis quo veniam incidunt odio, pariatur deserunt dicta nobis inventore nostrum corporis nesciunt, consequuntur quam dolorem facere itaque laudantium. Totam ea dolor dignissimos velit quas reprehenderit itaque quaerat, debitis aliquam repellat at ducimus in nemo repudiandae modi magni qui reiciendis doloribus pariatur odit sed nulla. Ullam sit officiis beatae tempore dolorum soluta accusantium non veniam iure. Temporibus, cumque est, assumenda harum debitis magnam ad quasi consectetur repudiandae, expedita deleniti impedit iste sed.</p>
<p>Harum amet a doloribus, nihil sed laudantium ab necessitatibus quibusdam modi eveniet voluptas corrupti, porro voluptates sint repudiandae veritatis quod eos minus? Rem impedit, assumenda sapiente maxime quia iste aut nihil. Molestias, laborum voluptate incidunt vel eveniet obcaecati minima. Accusantium temporibus culpa fuga rerum adipisci consequuntur, aliquid nisi vero earum ullam nihil facere in ex nulla odio molestias ipsa libero ducimus illo est harum. Sint repellat voluptates iure, sapiente perspiciatis? Earum cumque omnis, ea unde distinctio culpa optio. Cumque voluptas odit earum inventore error tempora, expedita maiores aliquam fuga, dolores, est quaerat excepturi ea quo blanditiis accusantium ullam laudantium animi!</p>
<p>Aliquam fugiat eveniet porro quisquam! Modi libero, ex quis voluptatum architecto reiciendis itaque officiis earum, eaque fuga reprehenderit perspiciatis voluptas sapiente iusto omnis sint id veniam incidunt ad asperiores. Aut velit id accusantium, nemo quo tempore quasi commodi optio ut. Ex pariatur, ipsa neque vel fugiat, deleniti ullam laudantium perspiciatis beatae nisi laborum, quod itaque. Facere dignissimos quae quibusdam aperiam, commodi fugiat doloremque, cumque porro, officiis sed asperiores natus, facilis tempora vel voluptas. Rerum debitis, blanditiis, facilis cum dignissimos voluptate. Possimus earum, deleniti veniam, iusto maiores architecto itaque eius voluptatibus at consequatur placeat, perferendis accusamus quidem. Quae architecto excepturi magni!</p>
<p>Reiciendis quae, quas quod odit, aliquam aut, suscipit repellat quibusdam iste libero corporis sapiente, sit temporibus! Necessitatibus a eius est quo, molestias consequuntur ipsum labore voluptatem voluptatibus, cupiditate fugit magnam voluptas velit quidem facilis nam similique minus tempora laudantium impedit vitae. Animi adipisci, vero quaerat officia velit ullam, eligendi quos quo voluptates quod quia aspernatur esse aut vel necessitatibus placeat odit reprehenderit voluptatem est enim fugit? Quos molestias velit nostrum iusto sunt eos adipisci ducimus quis rem iste cupiditate tenetur illum atque magni voluptatem, debitis voluptatibus, ea. Voluptate, quos ea placeat ipsa aspernatur perferendis, quidem esse, dolor temporibus rem quae.</p>
<p>Impedit adipisci reiciendis nihil, eos quibusdam suscipit exercitationem, ad, vitae reprehenderit, accusantium recusandae? Asperiores consectetur nesciunt modi nam corrupti expedita sequi nemo alias, accusamus laborum molestias quos iusto commodi tenetur. Non voluptatem, enim ratione. Quibusdam ad nisi atque recusandae, perspiciatis, facilis placeat labore facere quia doloremque perferendis quis vitae at deleniti fugiat assumenda debitis delectus, vero minus officiis. Rem enim, suscipit rerum nesciunt nemo consequatur quibusdam eius, sapiente facilis quidem corrupti repudiandae et alias officia ipsam numquam earum iste porro soluta commodi explicabo dolores esse facere, modi beatae! Ipsa minus ducimus quod officiis. Nostrum hic quis natus blanditiis harum in!</p>
</div>
</div>
</template>

<script>
export default {
    name:'dapartmentIndex'
}
</script>
<style scoped>
p{
    text-align: left;
    margin: 20px 0 0 20px
}
</style>