<template>
<div class="relative-wrap" >
    <div class="relative" style="background-color:#F7BA2A">
        <h2>回复管理</h2>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Fugit consequatur asperiores, molestias molestiae maiores perferendis. Fuga consectetur et nobis optio maxime reiciendis eaque ullam, blanditiis. Nesciunt ipsam architecto harum dolorum hic. Corporis tempora voluptates consequatur similique assumenda nisi amet aliquam vel deleniti animi illum iste, officiis rerum. Voluptas iste, quia necessitatibus dolorum inventore assumenda eos quaerat ut facere dolores laudantium atque repellendus quibusdam, tempore dolore nam temporibus optio, voluptates et id incidunt consequatur earum. Dolore, quaerat. Praesentium repellat, eligendi perspiciatis nihil magni consequuntur eum quam dolore cum omnis debitis id deleniti pariatur, aut, fugit atque animi facere nobis ullam tempore.</p>
        <p>Consequuntur optio culpa sit provident quod sunt soluta molestiae vitae molestias recusandae, eaque debitis nam quia, esse qui, incidunt asperiores suscipit tenetur ea facere, possimus aperiam dicta commodi beatae. Officiis nihil alias, porro ipsam! Voluptate iusto quis repellendus, labore recusandae quia ex cum eum enim suscipit, optio voluptas hic natus blanditiis nobis doloremque aut vitae ab unde exercitationem magnam neque voluptatem molestias excepturi! Vel, quibusdam ut dolorem laboriosam sequi quo eum deleniti numquam asperiores deserunt, amet, ratione cum minima veniam eligendi excepturi repellendus sint nulla at suscipit. Optio quidem accusantium quas ducimus nobis nisi porro, quia doloribus aut eveniet, nesciunt.</p>
        <p>Dolorem ab sint harum minima nam quos fugit, itaque corporis vero, dolorum soluta, distinctio quia? Quod placeat error, totam quas, praesentium nobis obcaecati rem mollitia incidunt delectus perferendis, eveniet facere! Voluptas necessitatibus, doloremque, rem perspiciatis odit consequuntur excepturi eum placeat perferendis vitae! Omnis sit mollitia obcaecati nobis tenetur, vero rem dolores sapiente quas nisi odio quibusdam voluptates, ducimus doloremque? Quo, esse iure tempore, fugit distinctio nemo tenetur mollitia vero consequatur vel odit at sint impedit. Eius ea tempora ex sint illo explicabo esse nam corrupti error, nihil fugit architecto deleniti neque facilis obcaecati culpa suscipit, a laborum odit. Quo, consequuntur.</p>
        <p>Magnam aliquam corrupti illo, nemo accusamus officiis quia! Blanditiis aspernatur, maxime a. Dicta, blanditiis! Pariatur quos, a repellendus odio repellat omnis sit qui ratione fugit veniam vitae dolorum repudiandae voluptatum soluta. Veritatis, at! Soluta similique explicabo in accusamus at, nobis, ullam repellat quo deleniti facere est. Optio voluptatibus, qui accusantium repudiandae eveniet sint laboriosam amet odit quidem corporis nam? Quaerat nemo unde reiciendis ipsam fuga voluptates aspernatur, nesciunt dignissimos inventore illo cupiditate eligendi nam deserunt doloremque laborum magni et necessitatibus nostrum, iure blanditiis! Architecto minus perspiciatis beatae iure incidunt aliquam error, possimus expedita a placeat nulla, veritatis eius, ut temporibus!</p>
        <p>Quo et ducimus laudantium sed magni nihil, voluptate quod ipsum eligendi, hic, facere molestias laboriosam dolores sequi porro. Error porro odio tempore. Obcaecati commodi dicta laboriosam, nulla recusandae praesentium quod corrupti ipsa nam hic vitae officia a nisi autem! Aspernatur laboriosam, excepturi. Vero ullam id dolor. Cumque sequi suscipit hic earum, magni, saepe et commodi natus libero aliquid quos numquam eligendi. Doloribus explicabo illo minus odit ipsum asperiores voluptatem molestiae quas aperiam nostrum debitis, assumenda sapiente delectus modi eius odio cum consectetur beatae praesentium, repellendus porro necessitatibus distinctio fugiat pariatur. Optio molestiae possimus soluta ex nihil aliquam magni, recusandae maxime!</p>
        <p>Quisquam totam debitis doloremque. Atque tempore voluptatem optio, provident molestias quidem minus minima quaerat numquam totam ipsum. Nostrum repellendus vel voluptates, eum repellat accusantium vero, eius odio et iste, aliquam nemo. Laboriosam culpa id iure, voluptates aliquam alias, quos consequatur, repellat temporibus enim laudantium placeat eum excepturi odit itaque obcaecati iste quia exercitationem qui nulla accusamus eligendi? Tenetur ex recusandae sunt numquam expedita cupiditate consequatur vel, ipsa, molestiae, quo aut. Et beatae alias, nostrum, veniam amet, expedita odio ab perspiciatis quis, ut quidem eum! Iure alias, sed quibusdam praesentium. Animi consequatur repellat ipsam, quo facere sint ipsa eaque et ab.</p>
        <p>Harum provident reprehenderit adipisci. Eius porro, amet repellat nisi quis tempora, culpa nulla, sed officia debitis reprehenderit. Sint officia quidem labore libero ratione placeat, unde? Quas alias quaerat quasi veritatis debitis labore. Ipsam similique nemo ratione impedit veniam animi perferendis cumque ipsa nisi fugit, enim consequatur. Vel labore, quisquam deserunt, doloribus laudantium officiis veritatis atque saepe obcaecati eius consectetur a! Quas, soluta eligendi et aspernatur sequi deleniti maxime eaque iusto, quibusdam dignissimos fugit. Fuga temporibus unde impedit, perferendis voluptate quisquam? Porro fugiat ab officiis architecto pariatur asperiores sit. Quod cum ab voluptatem earum officia laborum numquam dicta, placeat harum obcaecati.</p>
        <p>Dicta qui sunt dignissimos, quas deserunt sint cumque aut, exercitationem officiis quasi, sed expedita magni rem inventore cupiditate. Quaerat quis quod debitis cum deleniti voluptatum minus ullam. Magnam nemo illum eum quas et sunt autem cum facere hic dolorem dolorum itaque, cumque aliquid officia dolor culpa perspiciatis doloremque suscipit, quis eveniet. Necessitatibus quam aut molestias tempora accusamus praesentium autem corrupti quo repudiandae numquam magni soluta ipsa alias nihil enim ea explicabo, at hic quis. Mollitia ipsa adipisci itaque aliquam atque. Hic deserunt libero fugit sit tempora ea eveniet nobis magni ipsa, ducimus, ex similique incidunt quia eius modi omnis adipisci.</p>
        <p>Odit aut, magnam officia consequuntur corporis ratione, blanditiis optio nihil, dignissimos totam eum pariatur rerum laudantium? Ducimus reprehenderit doloribus deserunt officia nemo officiis nihil quas, accusamus, voluptates ratione molestiae blanditiis praesentium. Voluptatum eum laudantium harum, velit sapiente veritatis architecto animi in dolor mollitia vitae ea quos, quaerat blanditiis aut quisquam. Iusto hic ullam praesentium eius minima aspernatur, consectetur. Doloremque aut laboriosam hic cumque ratione dignissimos voluptatum quia, doloribus neque vero sit ab excepturi molestiae rem et eaque porro alias architecto? Tempora molestias eveniet nihil laborum error provident nemo accusamus, saepe temporibus quidem enim dolores officia, fugiat in culpa, dicta ipsum.</p>
        <p>Molestias eum itaque quas sit ratione. Ducimus rerum odit soluta quidem nisi quasi nihil quibusdam corrupti neque laborum fuga, laudantium reiciendis ipsa inventore eaque, porro sapiente quisquam veniam consectetur aliquam vero possimus ex. Dolorem id accusamus, similique eligendi, modi sed doloribus sequi ad voluptatem quae officia, quam qui molestias sapiente ipsa tempora vero blanditiis, nemo ut libero delectus temporibus. Quasi at, quibusdam! Natus magni dignissimos totam porro sapiente ipsam voluptatibus, fugiat eos quisquam, vitae reprehenderit eaque numquam autem expedita ipsa sint delectus id deserunt soluta optio consequatur accusantium. Facilis, reprehenderit. Voluptates soluta laboriosam delectus et, animi eos blanditiis incidunt nam!</p>
    </div>
</div>
</template>